---

- name: Config sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/98-sysctl.conf
    state: present
    reload: true
    sysctl_set: true
    ignoreerrors: true
  when: set_sysctl == true
  tags: 
    - sysctl
  with_items:
    - { name: 'net.ipv4.ip_forward', value: '1'}
    - { name: 'net.ipv4.ip_local_port_range', value: '1024 65000'}
    - { name: 'net.ipv4.tcp_mem', value: '94500000 915000000 927000000'}
    - { name: 'net.core.netdev_max_backlog', value: '262144'}
    - { name: 'net.ipv4.conf.all.arp_filter', value: '1'}
    - { name: 'net.ipv4.conf.default.arp_filter', value: '1'}
    - { name: 'net.ipv4.conf.all.rp_filter', value: '0'}
    - { name: 'net.ipv4.conf.default.rp_filter', value: '0'}
    - { name: 'net.ipv4.tcp_fastopen', value: '3'}
    - { name: 'net.ipv4.tcp_max_orphans', value: '262144'}
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: '262144'}
    - { name: 'net.ipv4.tcp_synack_retries', value: '1'}
    - { name: 'net.ipv4.tcp_syncookies', value: '1'}
    - { name: 'net.ipv4.tcp_tw_reuse', value: '1'}
    - { name: 'net.ipv4.tcp_tw_recycle', value: '1'}
    - { name: 'net.ipv4.tcp_max_tw_buckets', value: '100000'}
    - { name: 'net.ipv4.tcp_timestamps', value: '0'}
    - { name: 'net.ipv4.tcp_fin_timeout', value: '30'}
    - { name: 'net.ipv4.tcp_keepalive_time', value: '600'}
    - { name: 'net.ipv4.tcp_keepalive_probes', value: '3'}
    - { name: 'net.ipv4.tcp_keepalive_intvl', value: '15'}
    - { name: 'net.core.busy_read', value: '50'}
    - { name: 'net.core.busy_poll', value: '50'}
    - { name: 'net.netfilter.nf_conntrack_max', value: '41237300'}
    - { name: 'net.netfilter.nf_conntrack_tcp_timeout_established', value: '180'}
    - { name: 'vm.swappiness', value: '20'}
    - { name: 'vm.dirty_ratio', value: '40'}
    - { name: 'vm.dirty_background_ratio', value: '10'}
    - { name: 'vm.vfs_cache_pressure', value: '200'}
    - { name: 'kernel.pid_max', value: '4194304'}
    - { name: 'kernel.shmmax', value: '2147483648'}
    - { name: 'kernel.shmall', value: '134217728'}
    - { name: 'kernel.shmmni', value: '4096'}
    - { name: 'kernel.perf_event_max_sample_rate', value: '50000'}
    - { name: 'kernel.sched_min_granularity_ns', value: '10000000'}
    - { name: 'kernel.sched_wakeup_granularity_ns', value: '15000000'}


- name: Config limits
  lineinfile:
    path: /etc/security/limits.d/10-limits.conf
    create: true
    state: present
    line: "{{ item }}"
  when: set_limits == true
  tags: 
    - limits    
  with_items:
    - "*       soft    nofile    65535"
    - "*       hard    nofile    65535"
    - "*       soft    nproc    65535"
    - "*       hard    nproc    65535"
    - "*       soft    core     1048576"
    - "*       hard    core     1048576"
