---
# tasks file for common

- include: test.yml

- include: 01.base-config.yml
#- include_tasks: 01.base-config.yml

- include: 02.services-config.yml
  tags: services

- include: 03.optimize-config.yml
  tags: optimize

- include: 04.public-services.yml
  tags: public
